apiVersion: apps/v1
kind: Deployment
metadata:
  name: node1-app
  labels:
    app: node1-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node1-app
  template:
    metadata:
      labels:
        app: node1-app
    spec:
      containers:
      - name: node1-container
        image: us-central1-docker.pkg.dev/glass-sylph-477607-e9/node1-app/node1-app:381328d733f4ae8e089a8693d9fe44b056493d4d
        ports:
        - containerPort: 80
        