name: Deploy to GKE via GAR

on:
  push:
    branches:
      - hackathon # Trigger on pushes to the main branch



env:
  PROJECT_ID: "glass-sylph-477607-e9"
  CLUSTER_NAME: "gke-cluster"
  CLUSTER_LOCATION: "us-central1"
  GAR_REPOSITORY: "java-app"
  IMAGE_NAME: "java-app"
  IMAGE_TAG: "381328d733f4ae8e089a8693d9fe44b056493d4d" # Use Git commit SHA as image tag

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write' # Required for Workload Identity Federation

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 3: Authenticate with GCP
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}


      - name: Configure Docker to use gcloud as a credential helper
        run: |-
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Pull Docker image to GAR
        run: |
          
          docker pull "${CLUSTER_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${GAR_REPOSITORY}/${IMAGE_NAME}:${IMAGE_TAG}"

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.CLUSTER_NAME }}
          location: ${{ env.CLUSTER_LOCATION }}

      - name: Deploy to GKE
        working-directory: ./order-service/manifests
        run: |
          kubectl apply -f deployment.yaml
          kubectl set image deployment/${{ env.IMAGE_NAME }} ${{ env.IMAGE_NAME }}="${CLUSTER_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${GAR_REPOSITORY}/${IMAGE_NAME}:${IMAGE_TAG}" --record 
          kubectl rollout status deployment/${{ env.IMAGE_NAME }} -n default