name: Build Java App and Push to GCR

on:
  push:
    branches:
      - hackathon # Trigger on pushes to the main branch

defaults:
  run:
    working-directory: ./order-service

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven' # Cache Maven dependencies

      - name: Build Java application with Maven
        run: mvn clean package -DskipTests # Build the JAR, skipping tests for speed

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Configure Docker to use gcloud as a credential helper
        run: |-
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Build and push Docker image to GCR
        env:
          IMAGE_NAME: us-central1-docker.pkg.dev/glass-sylph-477607-e9/java-app:${{ github.sha }}
        run: |-
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME